export const iPhone14Pro = "/images/thai-nguyen-AtYWWis5ZDM-unsplash.jpg"
export const macBookProM3Max = "/images/d5dab80b-ab00-41f7-b2db-fd78c67d1969.jpeg"
export const canonEosR5 = "/images/36ae6c00-2dce-417e-a8d5-f19673f7edbd.jpeg"       
export const sonyWh1000xm5 = "/images/Sony WH-1000XM5 The Best Wireless Noise Canceling….jpeg"
export const samsungGalaxyS23Ultra = '/images/zana-latif-aVsbUg8UPvg-unsplash.jpg'
export const dell = "/images/yash-menghani-B_88OOFHTj8-unsplash.jpg"
export const visa = '/images/logo/visa.svg'
export const mastercard = '/images/logo/mastercard.svg'
export const paypal = '/images/logo/paypal.svg'
export const laptop2 ='/images/dmitry-chernyshov-mP7aPSUm7aE-unsplash.jpg'
export const laptop3 = '/images/maxim-hopman-Hin-rzhOdWs-unsplash.jpg'
export const laptop4 = '/images/devin-pickell-1eRS74C-alQ-unsplash.jpg'
export const jhon = '/images/charlie-green-3JmfENcL24M-unsplash.jpg'
export const sara = '/images/jake-nackos-IF9TK5Uy-KI-unsplash.jpg'
export const mike = '/images/ian-dooley-d1UPkiFd04A-unsplash.jpg'